version: "3.3"
services:
  cpp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpp-dev
    container_name: cpp-dev
    volumes:
      - type: bind
        source: ./contents
        target: /cpp-dev
    stdin_open: true
    tty: true
    working_dir: /cppdev